### ISSUE TITLE
Not debouncing

### ISSUE THREAD

**Issue by Donk3ys** [itsJoKr/debounced_text_form_field#1]
Maybe this is a stupid question but I can't get the debounce to work.

```
DebouncedTextFormField(
  validator: (val) => null,
  debounceDuration: const Duration(seconds: 5),
  decoration: const InputDecoration(hintText: "Test"),
  onChanged: (q) {
    log.debug(q);
   },
),
```

Shouldn't the onChanged be called after 5 seconds?

If i spam "d" input my logs return:
```
[debug] | 9:50:43 505ms | d
[debug] | 9:50:43 661ms | dd
[debug] | 9:50:43 833ms | ddd
[debug] | 9:50:43 955ms | dddd
```

Shouldn't the last log  be  the only one called and shouldn't it take 5 seconds from the first input?

**Comment by itsJoKr** [comment]
@Donk3ys The point of this package is that only the validation is debounced -> error text that is shown to the user.

OnChanged is called immediatelly on every text change, and sometimes you need that.

If you have
```dart
 validator: (val) => null,
 ```
 
 then this package has no use for you. Check the example to set real validator and observe how user will see debounced errors.

**Comment by Donk3ys** [comment]
Okay I understand now.

Missed this line in the docs 
/// - [onChanged] is called whenever the value changes, only errorText is being debounced.
